#version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./rules:/etc/prometheus/rules"
      - "./prometheus/data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"       
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "20000:9090"

  alertmanager:
    image: prom/alertmanager:latest
    restart: "always"
    ports:
      - "20002:9093"
    container_name: alertmanager
    volumes:
      - "./alert/alertmanager.yml:/etc/alertmanager/alertmanager.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "20001:3000"
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/grafana-storage:/var/lib/grafana"
