version : '3.8'
services:
  redis:
    container_name: redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/conf/redis.conf
      - ./redis/data:/data
    command: redis-server /conf/redis.conf