global:
  resolve_timeout: 5m
  smtp_from: '1191831992@qq.com'
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_auth_username: '1191831992@qq.com'
  smtp_auth_password: 'aikwjtihhyixfedd'
  smtp_require_tls: false
  smtp_hello: 'qq.com'

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5m
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: '1191831992@qq.com'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
